「Railsでユーザーフォローを作る」課題の提出物
Kassy0220/fjord-books_app pull request #5
Opened 2022-08-22 05:39 UTC by Kassy0220

「Railsでユーザーフォローを作る」課題の提出物を作成しましたので、ご確認をよろしくお願いいたします。

作成した課題は、次の要件に取り組んでいます。

+ ユーザー詳細画面にアクセスしてそのユーザーをフォローできるようにする（フォローボタンの設置）
+ すでにフォローしてる場合はフォロー解除できるようにする（フォロー解除ボタンの設置）
+ 自分自身のユーザー詳細画面ではフォローもフォロー解除もできない
+ ユーザー詳細画面に現在のフォロー数（そのユーザーがフォローしているユーザーの人数）とフォロワー数を表示する
+ ユーザー詳細画面からフォロー一覧画面に遷移できるようにする
+ ユーザー詳細画面からフォロワー一覧画面に遷移できるようにする
+ ユーザー詳細画面、フォロー一覧画面、フォロワー一覧画面のスクリーンショットを載せる

2022-08-27 06:56 UTC, u1tnk requested changes

2022-08-27 06:56 UTC, u1tnk commented on app/controllers/users_controller.rb
> +    @title = t('views.common.title_followings', user_name: @user.name)
これはviewに書けば良いと思います。

2022-08-28 10:47 UTC, Kassy0220 commented on app/controllers/users_controller.rb
> +    @title = t('views.common.title_followings', user_name: @user.name)
こちらのご指摘に関して、解決策を2つ考えました。

1. フォロイーとフォロワーを表示するビューファイルは共用のものを使う。

この場合、フォロイーのタイトルとフォロワーのタイトルを適宜変更しないといけないので、次のような形になるかなと考えました。
```ruby
<% if @users.some_method = 'active_followings' %>
  <h1><%= t('views.common.title_followings', user_name: @user.name) %></h1>
<% elseif @users.some_method = 'passive_followings' %>
  <h1><%= t('views.common.title_followers', user_name: @user.name) %></h1>
<% end %>
```

この`@users.some_method`の箇所で、関連名(`active_followings`または`passive_followings`)を取得する処理を`@users`に対して実行したかったのですが、どのような処理を書けば良いか分かりませんでした...。
`reflect_on_all_associations`など、Railsのアソシエーションに関するメソッドを探してみたのですがうまくできなかったので、こちらの方法は断念しました😢

2. フォロイーとフォロワーでビューファイルを分割する。

フォロイーとフォロワーを表示する各ファイルで、対応するタイトルを表示します。
今回はこちらの解決策を取りました。

https://github.com/Kassy0220/fjord-books_app/blob/6ddeb6d7094aba59bcb46016f28d70afe004c142/app/controllers/users_controller.rb#L17

https://github.com/Kassy0220/fjord-books_app/blob/6ddeb6d7094aba59bcb46016f28d70afe004c142/app/views/users/show_following.html.erb#L1-L3

https://github.com/Kassy0220/fjord-books_app/blob/6ddeb6d7094aba59bcb46016f28d70afe004c142/app/controllers/users_controller.rb#L25

https://github.com/Kassy0220/fjord-books_app/blob/6ddeb6d7094aba59bcb46016f28d70afe004c142/app/views/users/show_follower.html.erb#L1-L3

ユーザーを表示するパーシャル
https://github.com/Kassy0220/fjord-books_app/blob/6ddeb6d7094aba59bcb46016f28d70afe004c142/app/views/users/_follow_list.html.erb#L1-L9

2022-08-28 10:54 UTC, Kassy0220 commented
@u1tnk さん、ご確認ありがとうございます！

ご指摘の箇所を修正しましたので、ご確認をよろしくお願いいたします🙇🏻

2022-08-28 16:15 UTC, u1tnk reviewed
OKです！

viewは分割する方向で良いと思います。
基本的には viewで実行するものがcontrollerにあるのがNGというだけで、もっとスマートな方法もありますが、分割で十分と思います。

他に以下の方法が考えられますが分割で十分なので参考まで。
- current_userから見てfollwerかfollowee かを判別するメソッドをモデルなりに作る
- それぞれのviewの共通箇所を共通化する

2022-08-28 16:15 UTC, u1tnk approved these changes

2022-08-28 16:17 UTC, u1tnk requested changes
OKと書いたのですが、すみません一点まだありました、前回の修正の下なので一緒に指摘していたつもりでした。分かりづらかったですね。

2022-08-28 16:17 UTC, u1tnk commented on app/controllers/users_controller.rb
> +    @nobody_message = t('views.common.zero_followings', user_name: @user.name) if @users.empty?
ああ、すみません、ここも tメソッドを読んでいるのでviewに移動して欲しいです 🙏

2022-08-28 23:30 UTC, Kassy0220 commented on app/controllers/users_controller.rb
> +    @nobody_message = t('views.common.zero_followings', user_name: @user.name) if @users.empty?
`@nobody_message`の方も指摘箇所に含まれるのかどうか悩んで、そのままにしていました、すみません💦
コントローラーの`@nobody_message`を削除し、ビューで直接記述するように修正しました。

https://github.com/Kassy0220/fjord-books_app/blob/9e22e258d35fdac772c8a5c4192dbb8f439c488c/app/controllers/users_controller.rb#L12-L24

https://github.com/Kassy0220/fjord-books_app/blob/9e22e258d35fdac772c8a5c4192dbb8f439c488c/app/views/users/show_following.html.erb#L3

https://github.com/Kassy0220/fjord-books_app/blob/9e22e258d35fdac772c8a5c4192dbb8f439c488c/app/views/users/show_follower.html.erb#L3


> 基本的には viewで実行するものがcontrollerにあるのがNG

コントローラーとビューの役割をしっかり分ける、ということなのですね。
アドバイスを受けて改めてコードを見ると、コントローラーから`@nobody_message`を渡す意味がないことが分かります...。

2022-08-28 23:32 UTC, Kassy0220 commented
@u1tnk さん、再度のご確認ありがとうございます！

ご指摘の箇所を修正しましたので、ご確認をよろしくお願いいたします🙇🏻

2022-08-29 06:55 UTC, u1tnk approved these changes

2022-08-31 09:21 UTC, merged